In [1]:
import os
import time
import math
import cv2
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import mode
from sklearn.cluster import KMeans
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import datetime
from datetime import datetime as dt

import random

from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dense, Input, BatchNormalization, Dropout, Conv2D, Flatten

In [2]:
filepath = './horizontal/Video-15-47-49-515-31-03-2022/Video-15-47-49-515 (4IIC).mp4'
filepath_check = './checkpoint/'
input_dim = 500
maxCorners = 100
frames = 30
net_len = 1000
units = 100
output_size = 2
classes_list = ["stop", "go"]

In [3]:
horizontal = ['./horizontal/Video-7-36-30-868-22-03-2022/Video-7-36-30-868 (S1WK)',
            #'./horizontal/Video-10-6-45-47-30-03-2022/Video-10-6-45-47 (J57V)',
            './horizontal/Video-15-43-13-884-22-03-2022/Video-15-43-13-884 (J4NP)',
            './horizontal/Video-10-25-45-905-31-03-2022/Video-10-25-45-905 (3W3K)',
            './horizontal/Video-10-56-13-801-31-03-2022/Video-10-56-13-801 (X0N9)',            
            './horizontal/Video-11-19-18-132-30-03-2022/Video-11-19-18-132 (SH2G)',
            './horizontal/Video-12-51-53-673-27-03-2021/Video-12-51-53-673 (NKXJ)',
            #'./horizontal/Video-15-26-20-118-29-03-2022/Video-15-26-20-118 (5FLZ)',
            './horizontal/Video-15-32-33-709-31-03-2022/Video-15-32-33-709 (7BAA)',
            './horizontal/Video-15-41-30-94-29-03-2022/Video-15-41-30-94 (PH33)',
            #'./horizontal/Video-15-47-49-515-31-03-2022/Video-15-47-49-515 (4IIC)',
            './horizontal/Video-15-49-30-274-29-03-2022/Video-15-49-30-274 (JP92)',
            './horizontal/Video-15-8-58-789-27-03-2022/Video-15-8-58-789 (SSQM)',
            './horizontal/Video-17-14-15-118-06-03-2021/Video-17-14-15-118 (PE9P)',
            './horizontal/Video-17-34-45-652-25-03-2021/Video-17-34-45-652 (BK89)',
            './horizontal/Video-17-44-40-74-06-03-2021/Video-17-44-40-74 (CLNF)',
            './horizontal/Video-7-51-44-763-22-03-2022/Video-7-51-44-763 (1QN6)',
            './horizontal/Video-8-6-54-707-22-03-2022/Video-8-6-54-707 (PKAY)']

vertical = ['./vertical/Video-10-15-12-812-14-11-2020/Video-10-15-12-812 (2Y5M)',
           './vertical/Video-10-30-21-575-29-09-2021/Video-10-30-21-575 (UOM8)',
           './vertical/Video-11-21-2-419-13-09-2021/Video-11-21-2-419 (KVYG)',
           './vertical/Video-11-21-6-412-28-12-2020/Video-11-21-6-412 (JQQM)',
           './vertical/Video-11-36-12-363-28-09-2021/Video-11-36-12-363 (8119)',
           './vertical/Video-11-36-16-421-28-12-2020/Video-11-36-16-421 (PFAQ)',
           './vertical/Video-11-5-49-336-13-09-2021/Video-11-5-49-336 (CZPL)',
           './vertical/Video-12-23-51-640-02-10-2021/Video-12-23-51-640 (WLWK)',
           './vertical/Video-12-39-1-595-02-10-2021/Video-12-39-1-595 (QDUT)',
           './vertical/Video-12-44-36-682-24-09-2021/Video-12-44-36-682 (ATO6)',
           './vertical/Video-13-16-32-822-10-09-2021/Video-13-16-32-822 (UQ1Q)',
           './vertical/Video-13-20-30-695-15-11-2021/Video-13-20-30-695 (VLFO)',
           './vertical/Video-13-31-46-773-10-09-2021/Video-13-31-46-773 (MXM7)',
           './vertical/Video-16-16-44-458-17-11-2020/Video-16-16-44-458 (LCRL)',
           './vertical/Video-16-36-42-174-10-11-2020/Video-16-36-42-174 (IXTE)',
           './vertical/Video-16-47-10-870-17-11-2020/Video-16-47-10-870 (YFCN)',
           './vertical/Video-17-17-30-919-17-11-2020/Video-17-17-30-919 (ID6X)',
           './vertical/Video-17-32-40-752-17-11-2020/Video-17-32-40-752 (E575)',
           './vertical/Video-17-47-40-713-02-10-2021/Video-17-47-40-713 (E7IK)',
           './vertical/Video-20-21-59-727-24-09-2021/Video-20-21-59-727 (S04R)',
           './vertical/Video-20-45-56-152-24-10-2021/Video-20-45-56-152 (6M38)']

random.shuffle(horizontal)
random.shuffle(vertical)

videopath = horizontal# + vertical

random.shuffle(videopath)

In [4]:
def six_or_else(a):
    if a[1]==6:
        return [1,a[2]]
    else:
        return [0,a[2]]

def mode_periods(df):
    last_mode = -1
    mode_time = []
    mode_time.append([1 if df.iloc[0][0] == 6 else 0 , '00:00:00.0000000']) 
    for row in df.itertuples():  
        if row[1] != last_mode:   
            mode_time.append(six_or_else(row))
        last_mode = row[1]
    mode_time.append([1 if df.iloc[-1][0] == 6 else 0 , '1'+df.iloc[-1][1][1:] ] ) 
    
    return mode_time

In [5]:
def data(filepath):
    df = pd.read_csv(filepath[:-4]+'.csv')[['activityMode','timestamp']]
    mode_time = mode_periods(df)
    
    # Read the video 
    cap = cv2.VideoCapture(filepath)
    cap.set(cv2.CAP_PROP_BUFFERSIZE, 2)
    
    # Parameters for ShiTomasi corner detection
    feature_params = dict(maxCorners = maxCorners,
                       qualityLevel = 0.07,
                       minDistance = 10,
                       blockSize = 5 )

    # Parameters for Lucas Kanade optical flow
    lk_params = dict(winSize  = (15, 15),
                  maxLevel = 2,
                  criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03))
    net = []
    label_list = []
    i_frame = 0
    j_frame = 0
    while True:       
        ret, old_frame = cap.read()
        if not ret:
                break
        old_frame = cv2.resize(old_frame, (input_dim, input_dim))
        height, width, _ = old_frame.shape 
        part_width = round(width * 0.4)
        part_height = round(height * 0.4)
        
        old_gray = cv2.cvtColor(old_frame, cv2.COLOR_BGR2GRAY)
        
        p0 = cv2.goodFeaturesToTrack(old_gray, mask=None, **feature_params)
        cv2.rectangle(old_gray, (part_width, part_height), 
                          (width - part_width, height - part_height), 0, -1)
        # Create a mask image for drawing purposes
        mask = np.zeros_like(old_frame)
        
        while True:
            # Read new frame
            ret, frame = cap.read()
            
            if not ret:
                break
                
            sec = cap.get(cv2.CAP_PROP_POS_MSEC)
            res = datetime.timedelta(seconds = sec/1000)
            for i in range(len(mode_time)-1): 
                if (dt.strptime(mode_time[i][1][:-8], "%H:%M:%S") - datetime.datetime(1900, 1, 1) <= res) and\
                    (dt.strptime(mode_time[i+1][1][:-8], "%H:%M:%S") - datetime.datetime(1900, 1, 1) >= res):
                    label = [mode_time[i][0]]                
                    break  
                    
            if (len(label_list)!=0)and(label == label_list[-1])and(j_frame>maxCorners):
                continue 
                
            frame = cv2.resize(frame, (input_dim, input_dim))
            frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            cv2.rectangle(old_gray, (part_width, part_height), 
                          (width - part_width, height - part_height), 0, -1)
            # Calculate Optical Flow
            p1, st, err = cv2.calcOpticalFlowPyrLK(
                old_gray, frame_gray, p0, None, **lk_params
            )

            # Select good points
            good_new = p1[st == 1]
            good_old = p0[st == 1]
            
            new_net = good_new - good_old
            #print(new_net)
            while new_net.shape[0] < maxCorners:                
                new_net = np.append(new_net, [[0,0]], axis=0)                  
            new_net = np.array(new_net)
            new_net[np.lexsort((new_net[:,1],new_net[:,0]))]
            
            i_frame += 1
            
            if True:#(len(label_list)==0):
                j_frame += 1
                net.append(new_net) 
                label_list.append(label)
                # Update the previous frame and previous points
                old_gray = frame_gray.copy()
                p0 = good_new.reshape(-1, 1, 2)
                
                #if j_frame >= 100:
                   # break
                continue
            
            if ((label == label_list[-1]) and (j_frame<=frames)):
                j_frame += 1
                net.append(new_net) 
                label_list.append(label)
                # Update the previous frame and previous points
                old_gray = frame_gray.copy()
                p0 = good_new.reshape(-1, 1, 2)
                if j_frame >= frames:
                    break
                continue           
                        
            if (label != label_list[-1]):
                j_frame = 0
                net.append(new_net) 
                label_list.append(label)
                # Update the previous frame and previous points
                old_gray = frame_gray.copy()
                p0 = good_new.reshape(-1, 1, 2)
                break
                
    return np.array(net)/input_dim, np.array(label_list)

In [6]:
def data_full(filepath):
    df = pd.read_csv(filepath[:-4]+'.csv')[['activityMode','timestamp']]
    mode_time = mode_periods(df)
    
    # Read the video 
    cap = cv2.VideoCapture(filepath)
    cap.set(cv2.CAP_PROP_BUFFERSIZE, 2)
    
    # Parameters for ShiTomasi corner detection
    feature_params = dict(maxCorners = maxCorners,
                       qualityLevel = 0.07,
                       minDistance = 10,
                       blockSize = 5 )

    # Parameters for Lucas Kanade optical flow
    lk_params = dict(winSize  = (15, 15),
                  maxLevel = 2,
                  criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03))
    net = []
    label_list = []
    while True:       
        ret, old_frame = cap.read()
        
        if not ret:
                break
                
        old_frame = cv2.resize(old_frame, (input_dim, input_dim))
        height, width, _ = old_frame.shape 
        part_width = round(width * 0.4)
        part_height = round(height * 0.4)
        
        old_gray = cv2.cvtColor(old_frame, cv2.COLOR_BGR2GRAY)
        
        p0 = cv2.goodFeaturesToTrack(old_gray, mask=None, **feature_params)
        #cv2.rectangle(old_gray, (part_width, part_height), 
                          #(width - part_width, height - part_height), 0, -1)
        # Create a mask image for drawing purposes
        mask = np.zeros_like(old_frame)
        
        while True:
            # Read new frame
            ret, frame = cap.read()
            
            if not ret:
                break
                
            sec = cap.get(cv2.CAP_PROP_POS_MSEC)
            res = datetime.timedelta(seconds = sec/1000)
            for i in range(len(mode_time)-1): 
                if (dt.strptime(mode_time[i][1][:-8], "%H:%M:%S") - datetime.datetime(1900, 1, 1) <= res) and\
                    (dt.strptime(mode_time[i+1][1][:-8], "%H:%M:%S") - datetime.datetime(1900, 1, 1) >= res):
                    label = [mode_time[i][0]]                
                    break                    
                
            frame = cv2.resize(frame, (input_dim, input_dim))
            frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            #cv2.rectangle(old_gray, (part_width, part_height), 
                          #(width - part_width, height - part_height), 0, -1)
            # Calculate Optical Flow
            p1, st, err = cv2.calcOpticalFlowPyrLK(
                old_gray, frame_gray, p0, None, **lk_params
            )
            if p1 is None:
                break
            # Select good points
            good_new = p1[st == 1]
            good_old = p0[st == 1]
            
            new_net = good_new - good_old
            
            while new_net.shape[0] < maxCorners:                
                new_net = np.append(new_net, [[-999999,-999999]], axis=0) 
            #new_net = [[x[0] + input_dim,x[1] + input_dim] for x in new_net]
            #new_net = np.array(new_net)/(2*input_dim)
            new_net[np.lexsort((new_net[:,1],new_net[:,0]))]
            

            old_gray = frame_gray.copy()
            p0 = good_new.reshape(-1, 1, 2)
            
            net.append(new_net)
            label_list.append(label)
                
    return np.array(net), np.array(label_list)

In [43]:
def lucas_kanade_method_orig(video_path, callbacks, val_x, val_y):
    df = pd.read_csv(video_path[:-4]+'.csv')[['activityMode','timestamp']]
    mode_time = mode_periods(df)
    
    model = get_CNN(units, input_dim, output_size)
    
    model.compile(
        loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        optimizer="sgd",
        metrics=["accuracy"]
    )
    
    # Read the video 
    cap = cv2.VideoCapture(video_path)
    cap.set(cv2.CAP_PROP_BUFFERSIZE, 2)
    
    # Parameters for ShiTomasi corner detection
    feature_params = dict(maxCorners = maxCorners,
                       qualityLevel = 0.07,
                       minDistance = 7,
                       blockSize = 7 )

    # Parameters for Lucas Kanade optical flow
    lk_params = dict(winSize  = (15, 15),
                  maxLevel = 3,
                  criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03))

    # Create random colors
    color = np.random.randint(0, 255, (500, 3))
    predicted_class_name = ' '
    while True:       
        start = time.time()
        # Take first frame and find corners in it
        ret, old_frame = cap.read()
        old_frame = cv2.resize(old_frame, (input_dim, input_dim))
        height, width, _ = old_frame.shape 
        part_width = round(width * 0.3)
        part_height = round(height * 0.3)
        
        old_gray = cv2.cvtColor(old_frame, cv2.COLOR_BGR2GRAY)
        
        #cv2.rectangle(old_gray, (part_width, part_height), 
                          #(width - part_width, height - part_height), 0, -1)
        
        p0 = cv2.goodFeaturesToTrack(old_gray, mask=None, **feature_params)

        # Create a mask image for drawing purposes
        mask = np.zeros_like(old_frame)
        net = []
        label_list = []
        
        while True:
            # Read new frame
            ret, frame = cap.read()
            frame = cv2.resize(frame, (input_dim, input_dim))
            if not ret:
                break

            #cv2.rectangle(frame, (part_width, part_height), 
                          #(width - part_width, height - part_height), 0, -1)
            
            frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            # Calculate Optical Flow
            p1, st, err = cv2.calcOpticalFlowPyrLK(
                old_gray, frame_gray, p0, None, **lk_params
            )

            # Select good points
            good_new = p1[st == 1]
            good_old = p0[st == 1]
            
            new_net = good_new - good_old
            #print(new_net)
            while new_net.shape[0] < maxCorners:                
                new_net = np.append(new_net, [[-999999,-999999]], axis=0)                  
            new_net = np.array(new_net)
            new_net[np.lexsort((new_net[:,1],new_net[:,0]))]   
            net.append(new_net)
            
            # Draw the tracks
            for i, (new, old) in enumerate(zip(good_new, good_old)):
                a, b = new.ravel()
                c, d = old.ravel()
                mask = cv2.line(mask, (int(a), int(b)), (int(c), int(d)), color[i].tolist(), 2)
                frame = cv2.circle(frame, (int(a), int(b)), 5, color[i].tolist(), -1)

            sec = cap.get(cv2.CAP_PROP_POS_MSEC)
            res = datetime.timedelta(seconds = sec/1000)
            for i in range(len(mode_time)-1): 
                if (dt.strptime(mode_time[i][1][:-8], "%H:%M:%S") - datetime.datetime(1900, 1, 1) <= res) and\
                    (dt.strptime(mode_time[i+1][1][:-8], "%H:%M:%S") - datetime.datetime(1900, 1, 1) >= res):
                    label = [mode_time[i][0]]                
                    break  
            
            label_list.append(label)                
                
            # Display the demo
            img = cv2.add(frame, mask)
            cv2.putText(img, predicted_class_name, 
                        (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
            cv2.imshow("frame", img)
            k = cv2.waitKey(25) & 0xFF
            if k == 27:
                break

            # Update the previous frame and previous points
            old_gray = frame_gray.copy()
            p0 = good_new.reshape(-1, 1, 2)
            if np.array(net).shape[0] >= frames:
                net = np.array(net) / input_dim
                #history = model.fit(
                    #net, np.array(label_list), batch_size=20, epochs=1,
                    #callbacks=callbacks,
                    #validation_data  = (val_x, val_y) 
                #)
                predicted_labels_probabilities = model.predict(net)
                summa = predicted_labels_probabilities[0]
                print(predicted_labels_probabilities)
                for i in range(1, len(predicted_labels_probabilities)):
                    summa += predicted_labels_probabilities[i]
                #print(model.predict(net))
                predicted_label = np.argmax(summa)
        
                # Accessing The Class Name using predicted label.
                predicted_class_name = classes_list[predicted_label]
                
                break

In [8]:
val_x, val_y = data_full('./horizontal/Video-10-6-45-47-30-03-2022/Video-10-6-45-47 (J57V).mp4')
print(val_x.shape, val_y.shape)

(26707, 100, 2) (26707, 1)


In [44]:
checkpoint = keras.callbacks.ModelCheckpoint(
        filepath_check, monitor="val_accuracy",
        save_best_only=True, verbose=1,
        mode='max')
callbacks = [checkpoint]

In [10]:
def get_RNN(units, input_dim, output_size):
    model = keras.Sequential()
    model.add(layers.LSTM(units, return_sequences=True, input_shape=(None, 2)))
    model.add(layers.GRU(64))
    model.add(layers.Dropout(0.4))
    model.add(layers.Dense(32, activation="relu"))
    model.add(layers.Dense(output_size))

    return model

In [37]:
def get_CNN(units, input_dim, output_size): 
    model = keras.Sequential()
    #model.add(Conv2D(2, (2, 2), input_shape=(100, 2, 1)))
    model.add(Input((maxCorners,2)))
    model.add(Flatten())  
    #model.add(Dense(500, activation='relu')) 
    #model.add(Dropout(0.4))
    #model.add(BatchNormalization())
    #model.add(Dense(250, activation='relu'))
    #model.add(Dropout(0.4))
    #model.add(BatchNormalization())
    #model.add(Dense(100, activation='relu'))
    #model.add(Dropout(0.4))
    #model.add(BatchNormalization())
    model.add(Dense(55, activation='relu'))
    model.add(Dropout(0.4))
    model.add(BatchNormalization())
    model.add(Dense(2, activation='softmax'))
    
    
    return model

In [37]:
val_x_f, val_y_f = data_full('./horizontal/Video-15-47-49-515-31-03-2022/Video-15-47-49-515 (4IIC).mp4')
print(val_x_f.shape, val_y_f.shape)

(101, 100, 2) (101, 1)


In [12]:
# Adding Early Stopping Callback
early_stopping_callback = EarlyStopping(monitor = 'val_accuracy', patience = 15,
                                        mode = 'max', restore_best_weights = True)

model = get_CNN(units, input_dim, output_size)

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
                   metrics=['accuracy'])

2022-05-13 19:08:03.704868: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-05-13 19:08:03.704917: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (alexander-HP-Pavilion-Gaming-Laptop-15-cx0xxx): /proc/driver/nvidia/version does not exist
2022-05-13 19:08:03.706997: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [13]:
xt, yt = data_full('./horizontal/Video-15-26-20-118-29-03-2022/Video-15-26-20-118 (5FLZ).mp4')

In [ ]:
xt2, yt2 = data_full('./horizontal/Video-12-51-53-673-27-03-2021/Video-12-51-53-673 (NKXJ).mp4')

In [40]:
model.fit(
            xt, yt, batch_size=20, epochs=5,
            callbacks = callbacks,
            validation_data  = (val_x, val_y),
            shuffle = True
    
        )

model.fit(
            xt2, yt2, batch_size=20, epochs=5,
            callbacks = callbacks,
            validation_data  = (val_x, val_y),
            shuffle = True
    
        )

Epoch 1/5
 617/1322 [=============>................] - ETA: 1s - loss: 0.0143 - accuracy: 1.0000

KeyboardInterrupt: 

In [22]:
xx = np.concatenate((xt2, xt), 0)
yy = np.concatenate((yt2, yt), 0)

In [41]:
model.fit(
            xx, yy, batch_size=20, epochs=15,
            callbacks = callbacks,
            validation_data  = (val_x, val_y),
            shuffle = True
    
        )

Epoch 1/15
1933/1938 [============================>.] - ETA: 0s - loss: 0.6488 - accuracy: 0.6821
Epoch 1: val_accuracy improved from -inf to 0.67694, saving model to ./checkpoint/
INFO:tensorflow:Assets written to: ./checkpoint/assets
1938/1938 [==============================] - 6s 3ms/step - loss: 0.6487 - accuracy: 0.6821 - val_loss: 1643.5432 - val_accuracy: 0.6769
Epoch 2/15
1909/1938 [============================>.] - ETA: 0s - loss: 0.6263 - accuracy: 0.6820
Epoch 2: val_accuracy improved from 0.67694 to 0.75074, saving model to ./checkpoint/
INFO:tensorflow:Assets written to: ./checkpoint/assets
1938/1938 [==============================] - 5s 3ms/step - loss: 0.6261 - accuracy: 0.6821 - val_loss: 7379.3228 - val_accuracy: 0.7507
Epoch 3/15
1920/1938 [============================>.] - ETA: 0s - loss: 0.6262 - accuracy: 0.6822
Epoch 3: val_accuracy improved from 0.75074 to 0.75295, saving model to ./checkpoint/
INFO:tensorflow:Assets written to: ./checkpoint/assets
1938/1938 [===

In [47]:
lucas_kanade_method_orig('./horizontal/Video-15-43-13-884-22-03-2022/Video-15-43-13-884 (J4NP).mp4',
                         callbacks, val_x, val_x)

[[0.50000006 0.4999999 ]
 [0.500001   0.49999896]
 [0.49999306 0.5000069 ]
 [0.49999803 0.50000197]
 [0.50000757 0.49999243]
 [0.50000244 0.49999762]
 [0.49999633 0.50000364]
 [0.4999965  0.5000035 ]
 [0.50000304 0.49999702]
 [0.49999574 0.50000423]
 [0.4999967  0.5000033 ]
 [0.49999684 0.5000032 ]
 [0.50000197 0.49999806]
 [0.5000011  0.4999989 ]
 [0.50000125 0.49999875]
 [0.49999705 0.500003  ]
 [0.5000035  0.4999965 ]
 [0.50000274 0.49999732]
 [0.4999941  0.50000596]
 [0.5000003  0.49999973]
 [0.500004   0.49999604]
 [0.49999937 0.5000006 ]
 [0.5000011  0.4999989 ]
 [0.50001913 0.49998087]
 [0.5000062  0.49999383]
 [0.49999398 0.500006  ]
 [0.49999005 0.50000995]
 [0.50000054 0.49999943]
 [0.4999925  0.50000757]
 [0.49998882 0.50001115]]
[[0.4999994  0.5000006 ]
 [0.49999574 0.50000423]
 [0.50000787 0.4999922 ]
 [0.49999675 0.5000033 ]
 [0.49999312 0.50000685]
 [0.49999958 0.5000005 ]
 [0.49999702 0.50000304]
 [0.49999776 0.5000022 ]
 [0.49999917 0.50000083]
 [0.5000042  0.49999583]

[[0.4999995  0.50000054]
 [0.50000626 0.4999938 ]
 [0.5000005  0.49999958]
 [0.500002   0.49999794]
 [0.49999803 0.50000197]
 [0.5000045  0.4999955 ]
 [0.5000005  0.4999995 ]
 [0.50000286 0.49999717]
 [0.4999983  0.50000167]
 [0.5000002  0.4999998 ]
 [0.49999782 0.5000022 ]
 [0.4999992  0.50000083]
 [0.4999997  0.5000003 ]
 [0.49999514 0.5000049 ]
 [0.5000022  0.4999978 ]
 [0.49999648 0.5000035 ]
 [0.49999937 0.50000066]
 [0.49999824 0.5000017 ]
 [0.4999859  0.50001407]
 [0.49999613 0.50000393]
 [0.49999604 0.50000393]
 [0.49999744 0.5000026 ]
 [0.49999732 0.5000027 ]
 [0.50000507 0.49999496]
 [0.5000029  0.4999971 ]
 [0.5000028  0.49999717]
 [0.49999908 0.5000009 ]
 [0.49999863 0.5000014 ]
 [0.49999136 0.50000864]
 [0.5000015  0.4999985 ]]
[[0.5000016  0.49999836]
 [0.49999297 0.50000703]
 [0.49999902 0.500001  ]
 [0.5000045  0.4999955 ]
 [0.49999878 0.50000125]
 [0.5000004  0.49999964]
 [0.50000286 0.49999717]
 [0.49999318 0.50000685]
 [0.5000006  0.49999946]
 [0.5000009  0.49999908]

[[0.50000423 0.49999583]
 [0.500001   0.49999896]
 [0.5000046  0.49999547]
 [0.499997   0.50000304]
 [0.5000009  0.49999908]
 [0.49999782 0.50000215]
 [0.50000244 0.49999762]
 [0.5000035  0.4999965 ]
 [0.5000012  0.49999887]
 [0.49999705 0.500003  ]
 [0.50000024 0.49999982]
 [0.5000011  0.4999989 ]
 [0.4999989  0.5000011 ]
 [0.49999946 0.5000006 ]
 [0.5000007  0.4999993 ]
 [0.5000039  0.49999613]
 [0.5000005  0.49999952]
 [0.50000376 0.49999622]
 [0.500006   0.49999395]
 [0.4999957  0.5000043 ]
 [0.5000009  0.49999908]
 [0.4999989  0.5000011 ]
 [0.49999943 0.5000006 ]
 [0.50000364 0.49999636]
 [0.5000023  0.49999768]
 [0.49999642 0.5000036 ]
 [0.4999963  0.50000376]
 [0.49999586 0.5000041 ]
 [0.5000005  0.49999952]
 [0.5000032  0.49999678]]
[[0.49999967 0.5000003 ]
 [0.5000011  0.49999893]
 [0.49999753 0.50000244]
 [0.49999514 0.5000048 ]
 [0.49999955 0.5000005 ]
 [0.5000024  0.4999976 ]
 [0.49998605 0.50001395]
 [0.50000024 0.4999998 ]
 [0.4999963  0.5000037 ]
 [0.49999514 0.5000048 ]

[[0.5003432  0.49965683]
 [0.5001528  0.49984714]
 [0.4999298  0.50007015]
 [0.4999813  0.5000187 ]
 [0.49986205 0.500138  ]
 [0.49983153 0.5001685 ]
 [0.5001003  0.4998997 ]
 [0.5000838  0.4999162 ]
 [0.50005794 0.49994203]
 [0.5000654  0.49993458]
 [0.50053954 0.4994605 ]
 [0.50177515 0.49822485]
 [0.50265473 0.49734527]
 [0.49947652 0.50052345]
 [0.49771944 0.5022806 ]
 [0.49965242 0.5003476 ]
 [0.4989703  0.50102973]
 [0.49993727 0.5000627 ]
 [0.49972296 0.50027704]
 [0.4998019  0.5001981 ]
 [0.49924594 0.50075406]
 [0.49985504 0.500145  ]
 [0.49899852 0.50100154]
 [0.4986816  0.50131834]
 [0.49863866 0.50136137]
 [0.49867883 0.50132114]
 [0.49868348 0.5013165 ]
 [0.4985576  0.50144243]
 [0.498621   0.5013791 ]
 [0.4987848  0.5012151 ]]
[[0.49972713 0.50027287]
 [0.49970645 0.5002935 ]
 [0.4996321  0.50036794]
 [0.49973246 0.5002675 ]
 [0.49977946 0.50022054]
 [0.5000004  0.49999955]
 [0.49970728 0.5002927 ]
 [0.4995161  0.5004839 ]
 [0.49949735 0.5005026 ]
 [0.4995161  0.50048393]

[[0.49999353 0.50000644]
 [0.5000034  0.4999966 ]
 [0.5000016  0.49999845]
 [0.5000025  0.4999975 ]
 [0.49999252 0.5000075 ]
 [0.500002   0.49999794]
 [0.5000026  0.4999974 ]
 [0.4999983  0.50000167]
 [0.5000044  0.49999562]
 [0.5000027  0.49999738]
 [0.50000155 0.49999842]
 [0.5000023  0.49999768]
 [0.49999797 0.500002  ]
 [0.5000007  0.4999993 ]
 [0.49999887 0.5000012 ]
 [0.5000003  0.4999997 ]
 [0.50000083 0.49999923]
 [0.5000022  0.49999776]
 [0.49999726 0.50000274]
 [0.49999702 0.50000304]
 [0.49999937 0.5000006 ]
 [0.4999975  0.5000025 ]
 [0.4999971  0.50000286]
 [0.500002   0.49999803]
 [0.49999967 0.5000003 ]
 [0.5000028  0.49999717]
 [0.49999645 0.5000036 ]
 [0.49999973 0.50000024]
 [0.49999693 0.50000304]
 [0.499999   0.5000011 ]]
[[0.49999875 0.50000125]
 [0.5000053  0.4999947 ]
 [0.49999464 0.5000054 ]
 [0.5000025  0.4999975 ]
 [0.5000001  0.49999988]
 [0.4999967  0.5000033 ]
 [0.5000003  0.4999997 ]
 [0.49999943 0.5000006 ]
 [0.500003   0.49999702]
 [0.5000019  0.49999815]

[[0.5006003  0.49939972]
 [0.49947318 0.50052685]
 [0.5000861  0.4999139 ]
 [0.4999712  0.50002885]
 [0.50002325 0.49997672]
 [0.49999747 0.50000256]
 [0.50000286 0.4999971 ]
 [0.50006026 0.4999398 ]
 [0.49999598 0.50000405]
 [0.50000757 0.49999246]
 [0.49999928 0.5000007 ]
 [0.5001018  0.4998982 ]
 [0.49991968 0.5000803 ]
 [0.5000594  0.49994054]
 [0.500053   0.49994707]
 [0.49999133 0.50000864]
 [0.5000251  0.49997488]
 [0.49996945 0.5000305 ]
 [0.4997731  0.5002269 ]
 [0.5000495  0.4999506 ]
 [0.50017947 0.49982056]
 [0.5000467  0.49995336]
 [0.49993536 0.5000647 ]
 [0.5001546  0.49984545]
 [0.49997574 0.5000243 ]
 [0.49997234 0.50002766]
 [0.5000245  0.4999755 ]
 [0.49998292 0.5000171 ]
 [0.49999747 0.5000025 ]
 [0.49999845 0.50000155]]
[[0.49997407 0.5000259 ]
 [0.5000132  0.4999869 ]
 [0.50001544 0.49998456]
 [0.49996614 0.50003386]
 [0.4999975  0.50000256]
 [0.50000626 0.4999937 ]
 [0.5000108  0.4999892 ]
 [0.5000375  0.4999625 ]
 [0.5000103  0.4999897 ]
 [0.500001   0.49999905]

[[5.0211328e-01 4.9788669e-01]
 [5.0217092e-01 4.9782902e-01]
 [5.0236279e-01 4.9763715e-01]
 [5.0368732e-01 4.9631262e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [9.9935514e-01 6.4485468e-04]
 [9.9999928e-01 6.6856978e-07]
 [1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.000

[[0.4999001  0.50009984]
 [0.4999147  0.50008523]
 [0.49993053 0.50006944]
 [0.49999067 0.5000093 ]
 [0.50003004 0.49996993]
 [0.49998662 0.5000134 ]
 [0.50000316 0.4999968 ]
 [0.5000294  0.49997064]
 [0.49991834 0.5000816 ]
 [0.49996513 0.5000349 ]
 [0.5000036  0.49999648]
 [0.49998745 0.5000125 ]
 [0.4999439  0.5000561 ]
 [0.49993482 0.50006515]
 [0.4999187  0.50008124]
 [0.49991143 0.5000886 ]
 [0.50001055 0.49998948]
 [0.5000736  0.4999264 ]
 [0.5000517  0.49994835]
 [0.5000079  0.49999207]
 [0.50002486 0.49997512]
 [0.49999318 0.5000068 ]
 [0.5000055  0.4999945 ]
 [0.49993667 0.5000633 ]
 [0.49994138 0.50005865]
 [0.4999916  0.50000846]
 [0.49999762 0.50000244]
 [0.50001127 0.49998876]
 [0.5000138  0.49998623]
 [0.4999988  0.5000012 ]]
[[0.5000073  0.4999927 ]
 [0.49999428 0.5000058 ]
 [0.5000357  0.4999643 ]
 [0.5000007  0.49999925]
 [0.5000097  0.49999028]
 [0.4999869  0.5000132 ]
 [0.49999768 0.5000024 ]
 [0.49999797 0.500002  ]
 [0.4999939  0.5000061 ]
 [0.5000183  0.49998173]

[[0.499988   0.500012  ]
 [0.500013   0.499987  ]
 [0.50003225 0.49996772]
 [0.5000165  0.49998346]
 [0.5000325  0.49996752]
 [0.4999467  0.50005335]
 [0.49997544 0.5000246 ]
 [0.49994785 0.5000522 ]
 [0.49996212 0.5000379 ]
 [0.4999386  0.5000614 ]
 [0.49991098 0.500089  ]
 [0.49992952 0.5000705 ]
 [0.50001436 0.4999856 ]
 [0.49998188 0.5000181 ]
 [0.49998057 0.50001943]
 [0.49994105 0.50005895]
 [0.49988297 0.500117  ]
 [0.4999528  0.50004727]
 [0.50006866 0.4999313 ]
 [0.5000784  0.49992156]
 [0.5001356  0.49986446]
 [0.50004685 0.49995315]
 [0.5000082  0.49999183]
 [0.49989384 0.50010616]
 [0.49989522 0.5001047 ]
 [0.5000617  0.49993825]
 [0.49993625 0.5000638 ]
 [0.4999678  0.50003225]
 [0.4999129  0.5000871 ]
 [0.5000381  0.4999619 ]]
[[0.5000817  0.49991822]
 [0.500061   0.49993902]
 [0.5000539  0.49994612]
 [0.5001006  0.49989942]
 [0.5001946  0.49980533]
 [0.5002126  0.4997874 ]
 [0.5001987  0.49980128]
 [0.5001416  0.49985844]
 [0.5001346  0.4998655 ]
 [0.50014293 0.49985713]

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0.49992007 0.5000799 ]
 [0.4999544  0.5000456 ]
 [0.49980998 0.50018996]
 [0.49972937 0.5002706 ]
 [0.49915448 0.50084555]
 [0.49944663 0.5005533 ]
 [0.50009394 0.49990606]
 [0.49969488 0.5003052 ]
 [0.4998145  0.50018543]
 [0.49991167 0.50008833]
 [0.4998742  0.5001258 ]
 [0.49958247 0.50041753]
 [0.49960223 0.5003978 ]
 [0.49927828 0.50072163]
 [0.4992565  0.5007435 ]
 [0.49961463 0.50038534]
 [0.49909827 0.5009017 ]
 [0.49926287 0.50073713]
 [0.49957192 0.5004281 ]
 [0.49985155 0.5001485 ]
 [0.4990741  0.50092596]
 [0.4989996  0.5010004 ]
 [0.49916622 0.50083375]
 [0.49933615 0.5006639 ]
 [0.49922475 0.5007752 ]
 [0.49969745 0.50030255]
 [0.49989358 0.5001064 ]
 [0.49943706 0.500563  ]
 [0.49952987 0.50047004]
 [0.

[[0.49990484 0.5000952 ]
 [0.49990216 0.5000979 ]
 [0.4998779  0.5001222 ]
 [0.50005627 0.4999438 ]
 [0.49991158 0.5000884 ]
 [0.4999541  0.50004596]
 [0.49990395 0.5000961 ]
 [0.49991575 0.5000843 ]
 [0.49993205 0.50006795]
 [0.4999878  0.5000122 ]
 [0.49998283 0.50001717]
 [0.49986333 0.5001367 ]
 [0.49997917 0.50002086]
 [0.49988165 0.50011826]
 [0.49996963 0.5000304 ]
 [0.50033236 0.49966767]
 [0.5004121  0.4995879 ]
 [0.5003058  0.49969423]
 [0.49980825 0.5001917 ]
 [0.50009304 0.49990696]
 [0.49999177 0.5000082 ]
 [0.500076   0.49992403]
 [0.49997535 0.5000247 ]
 [0.49993074 0.50006926]
 [0.49994853 0.5000515 ]
 [0.49997634 0.5000237 ]
 [0.50005436 0.49994564]
 [0.5000783  0.49992162]
 [0.49996334 0.5000367 ]
 [0.49996933 0.5000307 ]]
[[0.49985245 0.5001476 ]
 [0.4999049  0.50009507]
 [0.49987707 0.500123  ]
 [0.49993268 0.5000673 ]
 [0.49985552 0.50014454]
 [0.49986407 0.500136  ]
 [0.49996015 0.5000398 ]
 [0.49985233 0.5001477 ]
 [0.49992362 0.50007635]
 [0.4999608  0.5000392 ]

[[0.50021243 0.4997876 ]
 [0.4998215  0.5001785 ]
 [0.5002692  0.49973083]
 [0.5001735  0.49982652]
 [0.49991348 0.5000865 ]
 [0.4999287  0.5000712 ]
 [0.49979675 0.50020325]
 [0.49920252 0.5007975 ]
 [0.49927709 0.500723  ]
 [0.4993025  0.5006975 ]
 [0.4992825  0.50071746]
 [0.49918962 0.50081044]
 [0.4988877  0.5011122 ]
 [0.49820027 0.50179976]
 [0.50089866 0.49910134]
 [0.50144255 0.49855754]
 [0.50022084 0.49977913]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]
[[0.49973786 0.50026214]
 [0.49966827 0.50033176]
 [0.49964482 0.5003552 ]
 [0.5000323  0.49996766]
 [0.5000893  0.49991068]
 [0.5001504  0.4998496 ]
 [0.50016487 0.49983516]
 [0.50001    0.49999005]
 [0.50024104 0.499759  ]
 [0.50007737 0.49992266]

[[0.49994975 0.50005025]
 [0.4999578  0.5000422 ]
 [0.4999318  0.5000681 ]
 [0.49993548 0.50006455]
 [0.4999403  0.5000597 ]
 [0.4999578  0.50004226]
 [0.49988106 0.5001189 ]
 [0.49992472 0.5000752 ]
 [0.49992296 0.50007707]
 [0.49989668 0.50010335]
 [0.49991196 0.500088  ]
 [0.49994877 0.5000512 ]
 [0.49988797 0.500112  ]
 [0.49977106 0.500229  ]
 [0.49976936 0.5002306 ]
 [0.4997937  0.5002063 ]
 [0.4998042  0.50019574]
 [0.49978146 0.50021863]
 [0.49970353 0.5002965 ]
 [0.4997282  0.5002718 ]
 [0.49994147 0.50005853]
 [0.4999852  0.50001484]
 [0.49994552 0.50005454]
 [0.50007683 0.49992314]
 [0.5000402  0.49995983]
 [0.5000557  0.4999443 ]
 [0.5000096  0.49999043]
 [0.5000208  0.49997926]
 [0.5000073  0.49999276]
 [0.49999934 0.50000066]]
[[0.4999516  0.50004846]
 [0.50015503 0.499845  ]
 [0.50022364 0.49977636]
 [0.50028056 0.4997194 ]
 [0.5002185  0.49978158]
 [0.50038385 0.4996161 ]
 [0.5002702  0.4997298 ]
 [0.5002691  0.49973083]
 [0.50023884 0.49976116]
 [0.50021416 0.49978587]

[[0.49997336 0.50002664]
 [0.4999854  0.50001466]
 [0.49997804 0.500022  ]
 [0.49998206 0.50001794]
 [0.49999627 0.50000376]
 [0.50004035 0.49995965]
 [0.5000919  0.49990812]
 [0.500146   0.49985403]
 [0.5001516  0.49984846]
 [0.5000675  0.4999325 ]
 [0.5002125  0.4997876 ]
 [0.5000514  0.49994862]
 [0.5000742  0.49992573]
 [0.5001023  0.4998977 ]
 [0.50012136 0.49987862]
 [0.5000706  0.4999294 ]
 [0.49949503 0.500505  ]
 [0.49958372 0.5004163 ]
 [0.4996268  0.50037324]
 [0.49975526 0.50024474]
 [0.49973807 0.5002619 ]
 [0.49971366 0.50028634]
 [0.49993664 0.50006336]
 [0.5000966  0.49990332]
 [0.50003123 0.49996883]
 [0.4998516  0.5001484 ]
 [0.499864   0.5001361 ]
 [0.4998748  0.5001253 ]
 [0.49986082 0.50013924]
 [0.49973682 0.50026315]]
[[0.49994105 0.50005895]
 [0.49978453 0.5002155 ]
 [0.49989587 0.50010407]
 [0.49996904 0.500031  ]
 [0.49998513 0.50001484]
 [0.4999796  0.50002044]
 [0.499939   0.500061  ]
 [0.4999457  0.5000543 ]
 [0.49987897 0.500121  ]
 [0.4999191  0.50008094]

[[4.9604672e-01 5.0395322e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [9.9935824e-01 6.4181362e-04]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1

[[0.49966487 0.50033516]
 [0.499425   0.500575  ]
 [0.5006741  0.4993259 ]
 [0.5001622  0.49983776]
 [0.50015336 0.49984667]
 [0.50039494 0.499605  ]
 [0.5001207  0.49987924]
 [0.5021397  0.49786034]
 [0.50179756 0.4982024 ]
 [0.49995846 0.5000416 ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
[[0.50126296 0.49873695]
 [0.50065196 0.49934798]
 [0.50115323 0.49884683]
 [0.5010209  0.49897912]
 [0.50201386 0.49798623]
 [0.5011916  0.49880847]
 [0.50112844 0.49887156]
 [0.5010753  0.49892473]
 [0.50087327 0.49912676]
 [0.50121397 0.49878603]

[[4.9950984e-01 5.0049019e-01]
 [4.9951649e-01 5.0048357e-01]
 [4.9964139e-01 5.0035858e-01]
 [4.9936122e-01 5.0063878e-01]
 [4.9959743e-01 5.0040251e-01]
 [4.9941474e-01 5.0058520e-01]
 [4.9953967e-01 5.0046033e-01]
 [4.9926817e-01 5.0073177e-01]
 [4.9909002e-01 5.0090998e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 1.1415303e-23]
 [9.9456637e-33 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[4.9835360e-01 5.0164646e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.000

[[0.50084835 0.4991517 ]
 [0.5009163  0.49908376]
 [0.5007468  0.4992532 ]
 [0.5008616  0.49913839]
 [0.50074524 0.49925482]
 [0.5007349  0.49926504]
 [0.50067174 0.49932832]
 [0.5006939  0.49930605]
 [0.5005732  0.49942675]
 [0.5007709  0.49922904]
 [0.50056076 0.4994393 ]
 [0.50049555 0.49950442]
 [0.5005557  0.4994443 ]
 [0.50060326 0.49939674]
 [0.50049525 0.4995047 ]
 [0.50049084 0.4995092 ]
 [0.50033295 0.49966702]
 [0.50055337 0.49944657]
 [0.50042    0.49958003]
 [0.5004381  0.49956188]
 [0.50036854 0.49963155]
 [0.5003648  0.49963522]
 [0.50037193 0.49962804]
 [0.5004171  0.49958286]
 [0.5002959  0.49970406]
 [0.5003674  0.4996327 ]
 [0.5003077  0.49969232]
 [0.5003762  0.49962375]
 [0.5002905  0.4997095 ]
 [0.50037605 0.49962395]]
[[0.49988732 0.50011265]
 [0.4999272  0.5000728 ]
 [0.49984252 0.5001575 ]
 [0.49987695 0.5001231 ]
 [0.49985096 0.5001491 ]
 [0.49988687 0.5001131 ]
 [0.4999105  0.5000895 ]
 [0.49988836 0.5001116 ]
 [0.49993262 0.5000674 ]
 [0.49993148 0.5000685 ]

[[0.500476   0.499524  ]
 [0.50060385 0.49939612]
 [0.5005341  0.49946597]
 [0.5005748  0.4994252 ]
 [0.50148517 0.4985148 ]
 [0.50084555 0.49915445]
 [0.500877   0.499123  ]
 [0.5005001  0.49949986]
 [0.50039965 0.4996003 ]
 [0.5004329  0.49956712]
 [0.50029564 0.49970436]
 [0.50026023 0.4997397 ]
 [0.50040567 0.4995944 ]
 [0.5004288  0.49957123]
 [0.5003463  0.4996537 ]
 [0.5004259  0.49957412]
 [0.5004047  0.49959525]
 [0.5009383  0.4990617 ]
 [0.5009862  0.49901384]
 [0.50092167 0.49907824]
 [0.5008078  0.49919224]
 [0.50093013 0.49906987]
 [0.5009891  0.49901095]
 [0.5009812  0.49901873]
 [0.50057167 0.49942833]
 [0.5006792  0.4993208 ]
 [0.5010343  0.4989657 ]
 [0.5010128  0.49898714]
 [0.4997705  0.5002295 ]
 [0.5007046  0.49929547]]
[[0.5008794  0.49912053]
 [0.50093484 0.4990651 ]
 [0.5009563  0.49904373]
 [0.5009497  0.4990503 ]
 [0.50102764 0.4989723 ]
 [0.5010275  0.4989725 ]
 [0.5016329  0.49836707]
 [0.50099677 0.4990032 ]
 [0.5010746  0.49892545]
 [0.5010926  0.49890736]

[[0.4997748  0.50022525]
 [0.49977475 0.50022525]
 [0.4997752  0.50022477]
 [0.49979532 0.5002046 ]
 [0.49976286 0.50023717]
 [0.49977857 0.5002215 ]
 [0.4997633  0.5002367 ]
 [0.4997871  0.5002129 ]
 [0.49980032 0.5001997 ]
 [0.49976385 0.5002362 ]
 [0.49975643 0.50024354]
 [0.49969152 0.50030845]
 [0.49974826 0.50025177]
 [0.49973685 0.5002631 ]
 [0.49961174 0.5003883 ]
 [0.49978992 0.50021005]
 [0.49967802 0.5003219 ]
 [0.499725   0.500275  ]
 [0.49970737 0.50029266]
 [0.4997268  0.5002733 ]
 [0.49962458 0.5003754 ]
 [0.49966514 0.50033486]
 [0.49961844 0.5003815 ]
 [0.49957353 0.5004265 ]
 [0.49961308 0.50038695]
 [0.49961987 0.5003801 ]
 [0.49963593 0.50036407]
 [0.49965513 0.5003448 ]
 [0.4995445  0.5004555 ]
 [0.4995637  0.50043625]]
[[0.4996782  0.50032175]
 [0.49978706 0.500213  ]
 [0.49969926 0.5003007 ]
 [0.49972293 0.5002771 ]
 [0.49985093 0.50014913]
 [0.4996447  0.5003553 ]
 [0.4996467  0.5003533 ]
 [0.49980873 0.5001912 ]
 [0.4996424  0.50035757]
 [0.499626   0.500374  ]

[[0.4999935  0.5000065 ]
 [0.49998936 0.50001067]
 [0.49998406 0.5000159 ]
 [0.49998116 0.5000189 ]
 [0.4999361  0.50006384]
 [0.49998587 0.5000141 ]
 [0.49998826 0.5000118 ]
 [0.49997652 0.5000235 ]
 [0.4999589  0.5000411 ]
 [0.4999761  0.5000239 ]
 [0.49997783 0.50002223]
 [0.49994293 0.50005704]
 [0.49993443 0.50006557]
 [0.49998993 0.50001013]
 [0.49996287 0.50003713]
 [0.50000364 0.49999636]
 [0.499919   0.500081  ]
 [0.4999797  0.5000203 ]
 [0.49994624 0.50005376]
 [0.49997166 0.5000284 ]
 [0.49993148 0.5000685 ]
 [0.5000035  0.4999965 ]
 [0.49993712 0.5000629 ]
 [0.49995142 0.5000486 ]
 [0.49999535 0.50000465]
 [0.49998105 0.500019  ]
 [0.49995828 0.5000418 ]
 [0.49999687 0.50000316]
 [0.4999509  0.5000492 ]
 [0.49994394 0.500056  ]]
[[0.4997826  0.50021744]
 [0.49979442 0.5002055 ]
 [0.49970955 0.50029045]
 [0.49968445 0.50031555]
 [0.49975106 0.5002489 ]
 [0.49976975 0.5002303 ]
 [0.49981016 0.5001898 ]
 [0.49975774 0.50024223]
 [0.49972105 0.500279  ]
 [0.49970835 0.5002917 ]

[[0.49999937 0.50000066]
 [0.5000191  0.49998096]
 [0.49997342 0.5000266 ]
 [0.49995837 0.5000416 ]
 [0.49997452 0.5000255 ]
 [0.499946   0.50005406]
 [0.49993327 0.5000667 ]
 [0.49997225 0.5000277 ]
 [0.4999604  0.50003964]
 [0.49997807 0.50002193]
 [0.50000215 0.49999788]
 [0.50000477 0.4999952 ]
 [0.4999923  0.50000775]
 [0.49996275 0.50003725]
 [0.49998015 0.5000199 ]
 [0.49993593 0.5000641 ]
 [0.4999847  0.5000153 ]
 [0.49998984 0.50001013]
 [0.4999716  0.5000284 ]
 [0.5000168  0.49998322]
 [0.50002444 0.49997556]
 [0.4999673  0.50003266]
 [0.49998236 0.5000177 ]
 [0.50000864 0.49999136]
 [0.49993742 0.5000626 ]
 [0.499955   0.50004506]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]
[[0.5000168  0.49998316]
 [0.49996257 0.50003743]
 [0.5000211  0.49997893]
 [0.49999386 0.5000062 ]
 [0.4999733  0.50002676]
 [0.49999708 0.500003  ]
 [0.4999801  0.50001997]
 [0.49999174 0.5000082 ]
 [0.499978   0.50002205]
 [0.49998504 0.500015  ]

[[0.5000107  0.49998927]
 [0.49999207 0.500008  ]
 [0.5000236  0.4999764 ]
 [0.49998033 0.5000197 ]
 [0.5000129  0.49998716]
 [0.4999697  0.5000303 ]
 [0.4999901  0.50000995]
 [0.49995255 0.5000475 ]
 [0.49999976 0.5000003 ]
 [0.4999907  0.50000936]
 [0.50000787 0.4999922 ]
 [0.5000099  0.49999008]
 [0.50000966 0.49999037]
 [0.49996337 0.5000366 ]
 [0.4999807  0.5000194 ]
 [0.4999976  0.50000244]
 [0.4999924  0.50000757]
 [0.49998274 0.5000172 ]
 [0.4999859  0.5000141 ]
 [0.5000061  0.49999395]
 [0.500008   0.499992  ]
 [0.49998292 0.5000171 ]
 [0.5000183  0.4999817 ]
 [0.49996993 0.5000301 ]
 [0.5000031  0.4999969 ]
 [0.5000061  0.49999395]
 [0.5000191  0.49998093]
 [0.50001043 0.49998963]
 [0.4999548  0.50004524]
 [0.49996257 0.50003743]]
[[0.4999819  0.5000181 ]
 [0.49999094 0.50000906]
 [0.50003767 0.49996236]
 [0.49998552 0.50001454]
 [0.50000775 0.49999228]
 [0.5000178  0.49998224]
 [0.49999276 0.5000073 ]
 [0.49996597 0.50003403]
 [0.50004876 0.49995127]
 [0.49998015 0.5000199 ]

[[0.49995047 0.5000496 ]
 [0.49998206 0.500018  ]
 [0.4999844  0.5000156 ]
 [0.49995762 0.5000424 ]
 [0.4999954  0.50000465]
 [0.49997777 0.5000223 ]
 [0.5000051  0.49999493]
 [0.4999994  0.5000006 ]
 [0.49995705 0.500043  ]
 [0.49994972 0.5000503 ]
 [0.4999792  0.5000208 ]
 [0.49992642 0.5000736 ]
 [0.49995765 0.5000423 ]
 [0.4999872  0.5000128 ]
 [0.49999508 0.50000495]
 [0.50003237 0.49996766]
 [0.4999633  0.50003666]
 [0.4999679  0.5000321 ]
 [0.4999916  0.50000846]
 [0.49997824 0.50002176]
 [0.49996307 0.5000369 ]
 [0.4999344  0.5000656 ]
 [0.499973   0.500027  ]
 [0.50002575 0.49997425]
 [0.50003797 0.499962  ]
 [0.50003666 0.49996337]
 [0.5000152  0.49998477]
 [0.5000133  0.49998668]
 [0.5000166  0.49998337]
 [0.49997932 0.50002074]]
[[0.50001884 0.49998122]
 [0.5000387  0.49996135]
 [0.5000211  0.4999789 ]
 [0.5000255  0.49997446]
 [0.5000174  0.4999826 ]
 [0.50001997 0.49998   ]
 [0.50002307 0.49997696]
 [0.50001603 0.49998397]
 [0.4999765  0.50002354]
 [0.50001955 0.4999805 ]

[[0.49943423 0.5005658 ]
 [0.4993544  0.50064564]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]
[[0.49996594 0.5000341 ]
 [0.5001022  0.4998978 ]
 [0.49996105 0.5000389 ]
 [0.49995276 0.5000472 ]
 [0.49995518 0.5000449 ]
 [0.49991855 0.5000815 ]
 [0.49993408 0.5000659 ]
 [0.49999028 0.5000097 ]
 [0.49991322 0.5000867 ]
 [0.4999636  0.50003636]

[[0.50000244 0.49999753]
 [0.49996847 0.5000316 ]
 [0.4999378  0.5000622 ]
 [0.5000336  0.49996635]
 [0.49999744 0.5000026 ]
 [0.5000245  0.49997547]
 [0.50006586 0.4999341 ]
 [0.5001155  0.4998845 ]
 [0.5001359  0.49986416]
 [0.500033   0.49996695]
 [0.5000203  0.49997967]
 [0.49994627 0.50005376]
 [0.49994963 0.5000504 ]
 [0.5000002  0.49999988]
 [0.5000396  0.49996045]
 [0.5000317  0.49996826]
 [0.5000215  0.4999785 ]
 [0.50008124 0.4999188 ]
 [0.5001108  0.49988914]
 [0.5000629  0.49993706]
 [0.5000488  0.4999512 ]
 [0.5000183  0.4999817 ]
 [0.4999904  0.50000966]
 [0.49996293 0.50003713]
 [0.4999849  0.5000151 ]
 [0.5000167  0.4999833 ]
 [0.50009185 0.4999081 ]
 [0.50008196 0.499918  ]
 [0.50010055 0.49989945]
 [0.5001054  0.49989456]]
[[0.4999683  0.50003177]
 [0.49993435 0.5000657 ]
 [0.4997815  0.5002186 ]
 [0.49991083 0.50008917]
 [0.49984077 0.50015926]
 [0.49984336 0.50015664]
 [0.49989808 0.50010186]
 [0.49992213 0.5000779 ]
 [0.49989152 0.5001084 ]
 [0.49992257 0.50007737]

[[1.0000000e+00 1.1397551e-23]
 [1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 

[[0.5013808  0.49861917]
 [0.5009264  0.49907362]
 [0.50058925 0.49941078]
 [0.5011075  0.49889246]
 [0.5009862  0.4990138 ]
 [0.501199   0.49880096]
 [0.50083923 0.49916077]
 [0.50090545 0.4990945 ]
 [0.50145876 0.4985412 ]
 [0.5010203  0.49897972]
 [0.4999174  0.50008255]
 [0.4992791  0.50072086]
 [0.49920145 0.5007985 ]
 [0.50002605 0.49997395]
 [0.49934885 0.5006512 ]
 [0.49955794 0.5004421 ]
 [0.500233   0.499767  ]
 [0.49943003 0.50056994]
 [0.49949354 0.50050646]
 [0.49990603 0.50009394]
 [0.4990209  0.5009791 ]
 [0.500608   0.49939194]
 [0.5007408  0.4992591 ]
 [0.5004793  0.49952078]
 [0.50030017 0.49969983]
 [0.5005562  0.4994438 ]
 [0.50015914 0.49984092]
 [0.5007035  0.49929655]
 [0.5006007  0.49939936]
 [0.5010389  0.49896103]]
[[0.5017994  0.4982006 ]
 [0.5017745  0.4982255 ]
 [0.5018435  0.49815652]
 [0.50154597 0.49845397]
 [0.50114423 0.49885577]
 [0.5020621  0.49793792]
 [0.5018722  0.49812782]
 [0.5021631  0.4978369 ]
 [0.5018912  0.49810883]
 [0.50151443 0.49848554]

[[4.9969757e-01 5.0030249e-01]
 [5.0076056e-01 4.9923944e-01]
 [4.9896106e-01 5.0103897e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 1.1283688e-23]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[5.0028694e-01 4.9971309e-01]
 [5.0029439e-01 4.9970558e-01]
 [5.001

[[4.9910429e-01 5.0089568e-01]
 [4.9890003e-01 5.0110000e-01]
 [4.9884829e-01 5.0115162e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [9.9936086e-01 6.3916674e-04]
 [9.9935883e-01 6.4118754e-04]
 [9.9936503e-01 6.3497975e-04]
 [9.9935800e-01 6.4196036e-04]
 [1.0000000e+00 1.1276804e-23]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[5.0138044e-01 4.9861956e-01]
 [5.0123632e-01 4.9876365e-01]
 [5.024

[[5.0003260e-01 4.9996743e-01]
 [4.9972957e-01 5.0027043e-01]
 [5.0023556e-01 4.9976450e-01]
 [4.9997300e-01 5.0002706e-01]
 [4.9969211e-01 5.0030792e-01]
 [5.0090069e-01 4.9909931e-01]
 [5.0054204e-01 4.9945796e-01]
 [5.0079215e-01 4.9920782e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 1.1276115e-23]
 [1.0000000e+00 1.1314032e-23]
 [1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1

[[0.49982035 0.5001797 ]
 [0.49977136 0.5002287 ]
 [0.49988776 0.50011224]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]
[[4.99740213e-01 5.00259817e-01]
 [5.00019431e-01 4.99980599e-01]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0

[[5.00473380e-01 4.99526709e-01]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [1.00131966e-32 1.00000000e+00]
 [1.00080031e-32 1.00000000e+00]
 [1.00199219e-32 1.00000000e+00]
 [1.00101418e-32 1.00000000e+00]
 [1.00123569e-32 1.00000000e+00]
 [9.99747219e-33 1.00000000e+00]
 [1.00106759e-32 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]]
[[0.50014

[[5.0187123e-01 4.9812883e-01]
 [5.0113630e-01 4.9886364e-01]
 [5.0180876e-01 4.9819115e-01]
 [5.0173038e-01 4.9826968e-01]
 [5.0081062e-01 4.9918938e-01]
 [5.0126410e-01 4.9873590e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [9.9935967e-01 6.4036675e-04]
 [9.9999928e-01 6.5847581e-07]
 [9.9999928e-01 6.6144651e-07]
 [1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[4.9811980e-01 5.0188017e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.000

[[4.9941307e-01 5.0058693e-01]
 [5.0010085e-01 4.9989909e-01]
 [5.0019807e-01 4.9980196e-01]
 [4.9853605e-01 5.0146401e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [9.9935776e-01 6.4229337e-04]
 [9.9935812e-01 6.4185268e-04]
 [9.9935967e-01 6.4029836e-04]
 [9.9935824e-01 6.4176467e-04]]
[[5.0010175e-01 4.9989823e-01]
 [4.9996415e-01 5.0003588e-01]
 [5.002

[[0.4999763  0.50002366]
 [0.50032973 0.49967033]
 [0.5002924  0.4997076 ]
 [0.50038826 0.49961174]
 [0.49999744 0.50000256]
 [0.49999857 0.5000015 ]
 [0.49995458 0.5000455 ]
 [0.49994162 0.50005835]
 [0.49994802 0.500052  ]
 [0.49998385 0.5000162 ]
 [0.50002325 0.49997675]
 [0.49998507 0.50001496]
 [0.49998507 0.5000149 ]
 [0.49997914 0.50002086]
 [0.49997878 0.5000213 ]
 [0.5000203  0.49997973]
 [0.49997956 0.5000205 ]
 [0.4999959  0.5000042 ]
 [0.49997756 0.5000225 ]
 [0.49997896 0.50002104]
 [0.50008714 0.49991286]
 [0.50004345 0.49995652]
 [0.49999917 0.5000009 ]
 [0.5000021  0.49999788]
 [0.4999653  0.5000347 ]
 [0.49999598 0.50000405]
 [0.5000034  0.49999663]
 [0.4999366  0.50006336]
 [0.49999902 0.50000095]
 [0.5000025  0.49999756]]
[[0.5000163  0.4999838 ]
 [0.4999926  0.50000745]
 [0.50000805 0.49999198]
 [0.5000256  0.49997446]
 [0.49997687 0.5000232 ]
 [0.5000205  0.4999795 ]
 [0.50001824 0.49998176]
 [0.49999413 0.50000584]
 [0.50000495 0.49999508]
 [0.4999979  0.5000021 ]

[[0.5007351  0.49926487]
 [0.5002477  0.49975234]
 [0.50031585 0.49968418]
 [0.5007389  0.49926108]
 [0.50075835 0.49924162]
 [0.5006851  0.49931496]
 [0.500476   0.49952406]
 [0.50103945 0.4989605 ]
 [0.50086427 0.49913576]
 [0.50082994 0.49917006]
 [0.5007631  0.49923697]
 [0.50061136 0.4993887 ]
 [0.5006569  0.499343  ]
 [0.5010946  0.49890545]
 [0.50062937 0.49937063]
 [0.50090146 0.49909854]
 [0.5008111  0.4991889 ]
 [0.5003009  0.49969915]
 [0.5004222  0.49957782]
 [0.4999422  0.50005776]
 [0.5001752  0.49982488]
 [0.49971443 0.5002856 ]
 [0.49984312 0.50015694]
 [0.50012827 0.4998718 ]
 [0.5006016  0.49939844]
 [0.5003977  0.49960235]
 [0.5013984  0.49860153]
 [0.5010088  0.49899122]
 [0.50083804 0.49916202]
 [1.         0.        ]]
[[0.50109947 0.49890053]
 [0.5011207  0.4988793 ]
 [0.5011474  0.4988526 ]
 [0.50111115 0.49888882]
 [0.50100505 0.49899498]
 [0.50087845 0.49912158]
 [0.50084716 0.4991529 ]
 [0.5008422  0.49915785]
 [0.5007527  0.49924728]
 [0.50101304 0.49898693]

[[5.0251371e-01 4.9748626e-01]
 [5.0294739e-01 4.9705261e-01]
 [5.0257242e-01 4.9742761e-01]
 [5.0374186e-01 4.9625817e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [9.9936074e-01 6.3921546e-04]
 [9.9936050e-01 6.3948851e-04]
 [9.9936229e-01 6.3769671e-04]
 [9.9935848e-01 6.4155919e-04]
 [9.9936002e-01 6.4002507e-04]
 [9.9936229e-01 6.3773565e-04]
 [9.9936050e-01 6.3947873e-04]
 [9.9936098e-01 6.3906936e-04]]
[[5.01140237e-01 4.98859763e-01]
 [5.00549853e-01 4.99450117e-01]
 [5

[[4.9984789e-01 5.0015211e-01]
 [4.9984169e-01 5.0015837e-01]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 1.1326469e-23]
 [1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
[[5.0040597e-01 4.9959412e-01]
 [5.0107747e-01 4.9892250e-01]
 [1.000

KeyboardInterrupt: 

In [15]:
for i in videopath:        
    x, y = data_full(i + '.mp4')   
      
    model.fit(
            np.array(x), np.array(y), batch_size=20, epochs=3,
            callbacks = callbacks,
            validation_data  = (val_x, val_y),
            shuffle = True 
    )

KeyboardInterrupt: 